FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiar archivo por archivo para evitar duplicados
COPY html/bandeja.html /usr/share/nginx/html/bandeja.html
COPY html/crear_solicitud.html /usr/share/nginx/html/crear_solicitud.html
COPY html/mis_solicitudes.html /usr/share/nginx/html/mis_solicitudes.html

COPY css/ /usr/share/nginx/html/css/
COPY js/ /usr/share/nginx/html/js/

EXPOSE 80
